import Foundation
import AppKit

enum ThinLincClientLauncher {
    private static let configBase: URL = {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let dir = appSupport.appendingPathComponent("ThinLincConnectionManager", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }()

    /// Writes a tlclient .conf for the given connection and returns the file URL, or nil on failure.
    static func writeConfig(for connection: Connection) -> URL? {
        let safeName = connection.name
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: "/", with: "-")
        let fileName = safeName.isEmpty ? "connection" : safeName
        let configURL = configBase.appendingPathComponent("tlclient_\(fileName).conf", isDirectory: false)

        let authMethod = connection.authType.lowercased().hasPrefix("key") ? "publickey" : "password"
        var lines = [
            "# ThinLinc client configuration",
            "# Generated by ThinLinc Connection Manager",
            "",
            "SERVER_NAME=\(connection.server)",
            "LOGIN_NAME=\(connection.username)",
            "AUTHENTICATION_METHOD=\(authMethod)",
        ]
        if connection.authType.lowercased().hasPrefix("key"), !connection.authData.isEmpty {
            lines.append("PRIVATE_KEY=\(connection.authData)")
        }

        let content = lines.joined(separator: "\n")
        guard let data = content.data(using: .utf8) else { return nil }
        do {
            try data.write(to: configURL)
            return configURL
        } catch {
            return nil
        }
    }

    /// Launches the ThinLinc client with the given connection, activating it in the foreground.
    /// The optional `completion` closure is called on the main thread once the client is running
    /// (or has failed to start), so it is safe to quit the app from there.
    static func launch(connection: Connection, completion: ((Bool) -> Void)? = nil) {
        guard let appURL = ThinLincClientFinder.findThinLincApp(),
              let configURL = writeConfig(for: connection) else {
            completion?(false)
            return
        }

        var arguments: [String] = ["-C", configURL.path]
        if connection.autoConnect {
            arguments += ["-p", "1"]
        }

        let config = NSWorkspace.OpenConfiguration()
        config.arguments = arguments
        config.activates = true
        config.createsNewApplicationInstance = true

        NSWorkspace.shared.openApplication(at: appURL, configuration: config) { _, error in
            DispatchQueue.main.async {
                completion?(error == nil)
            }
        }
    }
}
